# test java version of library
name: Test Java

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11  # first LTS version that can accept --release arg; needed so we can for compiler to use that version of bytecode
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Install pipelines-jar
        run: mvn install:install-file -Dfile=java/lib/pipeline.jar -DgroupId=com.google.appengine.tools -DartifactId=appengine-pipeline -Dversion=0.3+worklytics.4 -Dpackaging=jar
      # init maven settings such maven can consume packages from GitHub, not just maven central
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          override: true
          servers: '[{"id": "github", "username": "OWNER", "password": "${{secrets.GITHUB_TOKEN}}"}]'
      # do actual build + test run
      - name: Build with Maven
        run: |
          cd java/
          mvn test
        env:
          APPENGINE_MAPREDUCE_CI_SERVICE_ACCOUNT_KEY: ${{ secrets.APPENGINE_MAPREDUCE_CI_SERVICE_ACCOUNT_KEY }}
